'use client'

import { createContext, useContext, useState, ReactNode, useEffect } from 'react'

type Language = 'en' | 'zh' // English first as default

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

// Translation keys and values
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & General
    'nav.dashboard': 'Dashboard',
    'nav.transactions': 'Transactions',
    'referral.title': 'Invite Friends',
    'referral.subtitle': 'Get free Pro access',
    'referral.share_button': 'Share Invite Link',
    'referral.stats_title': 'Your Referrals',
    'referral.viral_share_wechat': '我用 FinleyBook 省了快 $300，送你 30 天 Pro 随便用！[链接]',
    'referral.viral_share_whatsapp': 'This app saved me $127 last month - 30 days Pro free for you! [link]',
    'nav.budget': 'Budget',
    'nav.goals': 'Goals',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.subscription': 'Subscription',
    'nav.about': 'About',
    'nav.blog': 'Blog',
    'nav.terms': 'Terms',
    'nav.privacy': 'Privacy',
    'nav.signOut': 'Sign Out',
    'nav.rewards': 'Insights Hub',
    'nav.searchPlaceholder': 'Search wealth, products...',
    'nav.me': 'Me',

    // Dashboard
    'dashboard.title': 'Financial Overview',
    'dashboard.date': '{date}',
    'dashboard.totalAssets': 'Total Assets',
    'dashboard.monthlyIncome': 'Monthly Income',
    'dashboard.monthlyExpenses': 'Monthly Expenses',
    'dashboard.savingsRate': 'Savings Rate',
    'dashboard.cumulativeNetAssets': 'Cumulative Net Assets',
    'dashboard.monthlyTotalExpenses': 'Monthly Total Expenses',
    'dashboard.monthlySavingsRatio': 'Monthly Savings Ratio',
    'dashboard.totalIncome': 'Total Income',
    'dashboard.totalExpenses': 'Total Expenses',
    'dashboard.netIncome': 'Net Income',
    'dashboard.welcomeBack': 'Welcome back, {name}!',
    'dashboard.wealthCommandCenter': 'Your Wealth Command Center',
    'dashboard.proAd.title': 'Upgrade to Pro',
    'dashboard.proAd.desc': 'Unlock unlimited transactions, AI insights, and custom categories.',
    'dashboard.pendingCashback': 'Pending Cashback',
    'dashboard.actionPotential': 'Action Potential',
    'dashboard.actionPotentialDescription': 'Estimated monthly optimization',
    'dashboard.finleyFocusScore': 'Finley Focus Score',
    'dashboard.focusScoreDescription': 'How ready your money system is',
    'dashboard.nextMoveSignature': 'Finley One-Move Engine™',
    'dashboard.nextMoveImpact': 'Estimated monthly impact',
    'dashboard.nextMoveDoNow': 'Do This Now',
    'dashboard.nextMoveAskAI': 'Ask AI Why',
    'dashboard.nextMoveShare': 'Share Plan',
    'dashboard.nextMoveCopied': 'Plan copied. Share it with friends.',
    'dashboard.nextMoveShareTemplate': 'My Finley Next Move: {title}. {impact}. Try it here: {url}',
    'dashboard.cashFlow': 'Cash Flow Trend',
    'dashboard.smartSuggestions': 'Smart Suggestions',
    'dashboard.wealthVault.earnings': 'Total Earnings',
    'dashboard.budget.shopSave': 'Planning to shop? Save {rate} at {merchant}.',
    'dashboard.profitOrb.label': 'Earned This Month',
    'dashboard.profitOrb.sublabel': 'Profit Center',

    // Charts
    'charts.expenseBreakdown': 'Expense Breakdown',
    'charts.incomeVsExpense': 'Income vs Expense',
    'charts.income': 'Income',
    'charts.expense': 'Expense',
    'charts.amount': 'Amount',
    'charts.noData': 'No transaction data available',
    'charts.others': 'Others',

    // Recent Transactions
    'transactions.recent': 'Recent Transactions',
    'transactions.addTransaction': 'Add Transaction',
    'transactions.noRecords': 'No transaction records',
    'transactions.startAdding': 'Start adding your first transaction',
    'transactions.showMore': 'View more transactions',
    'transactions.showLess': 'Show recent 10',
    'transactions.subtitle': 'Manage your income and expenses',
    'transactions.noResults': 'No transactions found matching your search',
    'transactions.title': 'Transactions',
    'transactions.add': 'Add Transaction',

    // Transaction Modal
    'transaction.add': 'Add Transaction Record',
    'transaction.type': 'Transaction Type',
    'transaction.income': '💰 Income',
    'transaction.expense': '💸 Expense',
    'transaction.amount': 'Amount *',
    'transaction.category': 'Category *',
    'transaction.selectCategory': 'Select category',
    'transaction.description': 'Description *',
    'transaction.descriptionPlaceholder': 'Transaction description',
    'transaction.date': 'Date',
    'transaction.paymentMethod': 'Payment Method',
    'transaction.cancel': 'Cancel',
    'transaction.submit': 'Add Transaction',
    'transaction.submitting': 'Adding...',
    'transaction.success': 'Transaction Added Successfully!',
    'transaction.successMessage': 'Transaction record added successfully',
    'transaction.error': 'Failed to add transaction record',

    // Payment Methods
    'payment.cash': 'Cash',
    'payment.bankCard': 'Bank Card',
    'payment.alipay': 'Alipay',
    'payment.wechat': 'WeChat Pay',
    'payment.creditCard': 'Credit Card',
    'payment.other': 'Other',

    // Categories - Income
    'category.salary': 'Salary Income',
    'category.investment': 'Investment Returns',
    'category.parttime': 'Part-time Income',
    'category.otherIncome': 'Other Income',

    // Categories - Expense
    'category.food': 'Food & Dining',
    'category.transport': 'Transportation',
    'category.shopping': 'Shopping',
    'category.housing': 'Housing & Utilities',
    'category.health': 'Health & Medical',
    'category.entertainment': 'Entertainment',
    'category.education': 'Education',
    'category.otherExpense': 'Other Expenses',

    // Quick Actions
    'quickActions.title': 'Quick Actions',
    'quickActions.subtitle': 'Select an action to start',
    'quickActions.addTransaction': 'Add Transaction',
    'quickActions.addTransactionDesc': 'Manually record income/expense',
    'quickActions.scanReceipt': 'Scan Receipt',
    'quickActions.scanReceiptDesc': 'Auto-recognize via photo',
    'quickActions.voiceInput': 'Voice Input',
    'quickActions.voiceInputDesc': 'Quick record by speaking',
    'quickActions.viewTransactions': 'View Transactions',
    'quickActions.viewTransactionsDesc': 'Browse transaction details',
    'quickActions.inviteFriend': 'Invite Friend',
    'quickActions.inviteFriendDesc': 'Get Pro membership',

    // Budget
    'budget.overBudget': 'Over budget by {amount}',
    'budget.emptyTitle': 'No Budgets Yet',
    'budget.emptyDesc': 'Set monthly spending limits to track your savings goals.',
    'budget.createFirst': 'Create First Budget',

    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.signInDescription': 'Sign in to continue using your smart financial assistant',
    'auth.signUpDescription': 'Start your smart financial management journey',
    'auth.googleSignIn': 'Continue with Google',
    'auth.continueEmail': 'Continue with Email',
    'auth.signup': 'Sign Up',
    'auth.login': 'Login',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': 'No account?',
    'auth.or': 'OR',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.passwordSignUpPlaceholder': 'At least 6 characters',
    'auth.confirmPasswordPlaceholder': 'Enter password again',
    'auth.processing': 'Processing...',
    'auth.signInSuccess': 'Sign in successful!',
    'auth.signUpSuccess': 'Sign up successful!',
    'auth.googleSignInSuccess': 'Google sign in successful!',
    'auth.signInError': 'Sign in failed, please check email and password',
    'auth.signUpError': 'Sign up failed, please try again later',
    'auth.googleSignInError': 'Google sign in failed',
    'auth.enterEmailFirst': 'Please enter your email first',
    'auth.passwordResetSent': 'Password reset email sent! Check your inbox.',
    'auth.passwordResetError': 'Failed to send password reset email',

    // Form Validation
    'validation.emailRequired': 'Please enter email address',
    'validation.emailInvalid': 'Please enter a valid email address',
    'validation.passwordRequired': 'Please enter password',
    'validation.passwordTooShort': 'Password must be at least 6 characters',
    'validation.confirmPasswordRequired': 'Please confirm password',
    'validation.passwordMismatch': 'Passwords do not match',
    'validation.amountRequired': 'Please enter a valid amount',
    'validation.categoryRequired': 'Please select transaction category',
    'validation.descriptionRequired': 'Please enter transaction description',
    'validation.dateRequired': 'Please select transaction date',

    // Landing Page
    'landing.title': 'Smart Financial Management with AI',
    'landing.subtitle': 'Take control of your finances with intelligent insights, automated tracking, and personalized recommendations',
    'landing.getStarted': 'Get Started Free',
    'landing.learnMore': 'Learn More',
    'landing.features.tracking': 'Smart Tracking',
    'landing.features.insights': 'AI Insights',
    'landing.features.budgeting': 'Smart Budgeting',
    'landing.features.security': 'Bank-Level Security',

    // New Landing Page (Financial Navigator)
    'landing.badge': 'Money Management, Gamified',
    'landing.hero.title.prefix': 'Save Money. ',
    'landing.hero.title.highlight': 'Earn Cashback. Build Wealth.',
    'landing.hero.desc': 'The first finance tracker that pays you back. Complete simple tasks, shop smart, and watch your savings grow automatically.',
    'landing.cta.start': 'Start Saving Money Now',
    'landing.hero.sub': 'Bank-Level Security · No Credit Card Required',
    'landing.features.badge': 'Why Choose FinleyBook',
    'landing.features.title': 'Smart Cashback & Tracking',
    'landing.features.desc': 'Experience the future of personal finance. We help you save on what you spend.',
    'landing.feature.safe.title': 'Safe-to-Spend',
    'landing.feature.safe.desc': 'Know exactly how much you can spend today. Green means safe, red means stop.',
    'landing.feature.drag.title': 'Smart Cashback',
    'landing.feature.drag.desc': 'Shop through FinleyBook and get up to 15% cash back. Your subscription pays for itself.',
    'landing.feature.time.title': 'Time Machine',
    'landing.feature.time.desc': 'See your future wealth based on current habits. Will you be rich or broke?',
    'landing.trust.users': 'Trusted by 10,000+ Users',
    'landing.trust.security': 'Bank-Level Security',
    'landing.trust.privacy': '100% Private & Encrypted',
    'landing.calculator.title': 'How much could you save?',
    'landing.calculator.spend': 'Monthly Online Spend',
    'landing.calculator.result': 'With FinleyBook, you could save <span class="text-indigo-600 font-bold">{amount}/mo</span> + Keep your budget on track.',

    // Onboarding Guide
    'guide.title': 'Quick Start',
    'guide.step.transaction.title': 'Add First Transaction',
    'guide.step.transaction.desc': 'Record your first income or expense',
    'guide.step.transaction.action': 'Add Now',
    'guide.step.export.title': 'Export Data',
    'guide.step.export.desc': 'Download your financial reports as PDF or CSV',
    'guide.step.export.action': 'Go to Reports',
    'guide.step.cashback.title': 'Run Weekly Review',
    'guide.step.cashback.desc': 'Review spending and apply one optimization action',
    'guide.step.cashback.action': 'Open Reports',
    'guide.step.profile.title': 'Complete Profile',
    'guide.step.profile.desc': 'Set up your preferences and goals',
    'guide.step.profile.action': 'Go to Settings',
    'guide.progress': '{current}/{total} Completed',
    'guide.dismiss': 'Dismiss Guide',

    // Onboarding
    'onboarding.identity.title': 'What is your focus right now?',
    'onboarding.identity.survival.title': 'Building Foundations',
    'onboarding.identity.survival.desc': 'I want to stop living paycheck to paycheck.',
    'onboarding.identity.shopaholic.title': 'Lifestyle Optimizer',
    'onboarding.identity.shopaholic.desc': 'I enjoy spending, but want to earn rewards back.',
    'onboarding.identity.saver.title': 'Strategic Grower',
    'onboarding.identity.saver.desc': 'I\'m aggressive about saving and investing.',
    'onboarding.pain.title': 'Let\'s find your hidden wealth.',
    'onboarding.pain.desc': 'Estimated monthly impulse spending?',
    'onboarding.pain.min': '{amount} (Peanuts)',
    'onboarding.pain.max': '{amount}+ (Help!)',
    'onboarding.pain.annual': 'Invested at 5%, this is',
    'onboarding.pain.next': 'Next',
    'onboarding.dream.title': 'If we could recover this...',
    'onboarding.dream.desc': 'By next year, you could have:',
    'onboarding.dream.inputTitle': 'Let\'s make it happen.',
    'onboarding.dream.inputDesc': 'Setting a goal increases your chance of success by 80%.',
    'onboarding.dream.submitFrom': 'Set My Goal',
    'onboarding.dream.ipad': 'An iPad Air',
    'onboarding.dream.flight': 'A Round-trip Flight',
    'onboarding.dream.rent': '3 Months of Rent',
    'onboarding.dream.value': 'Value approx. {amount}',
    'onboarding.dream.cta': 'Take me to find this money',
    'onboarding.final.title': 'Last Step',
    'onboarding.final.desc': 'One second to open your "Flight Fund".',
    'onboarding.final.google': 'Start with Google',
    'onboarding.final.terms': 'By clicking, you agree to our Terms',



    // Language Settings
    'language.title': 'Language Settings',
    'language.description': 'Choose your preferred language for the interface',
    'language.english': 'English',
    'language.chinese': '简体中文 (Chinese)',
    'language.current': 'Current Language',
    'language.save': 'Save Changes',
    'language.saved': 'Language preference saved',

    // Landing Page Legacy (for backward compatibility)
    'nav.login': 'Log In',
    'nav.register': 'Sign Up',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'hero.title_prefix': 'AI-Driven',
    'hero.title_highlight': 'Personal Finance',
    'hero.title_suffix': 'Platform',
    'hero.description': 'An AI financial assistant integrating smart bookkeeping, financial analysis, and tax management. Making complex financial management simple and smart, helping you achieve financial freedom.',
    'hero.start': 'Get Started',
    'hero.learn_more': 'Learn More',
    'features.title': 'Smart Financial Management',
    'features.subtitle': 'Core Features',
    'features.description': 'Centering on data aggregation, smart analysis, risk warning, and personalized services, providing deep value beyond traditional bookkeeping software.',
    'features.items.aggregation.title': 'Smart Data Aggregation',
    'features.items.aggregation.desc': 'Automatically aggregate bank accounts and payment platform data, OCR receipt recognition, supporting natural language bookkeeping.',
    'features.items.analysis.title': 'Smart Analysis & Prediction',
    'features.items.analysis.desc': 'AI-based personalized financial analysis, cash flow forecasting, and smart budget suggestions.',
    'features.items.tax.title': 'Tax Risk Warning',
    'features.items.tax.desc': 'Real-time monitoring of tax compliance risks, invoice verification, duplicate reimbursement detection, and policy change alerts.',
    'features.items.ai.title': 'AI Smart Assistant',
    'features.items.ai.desc': '24/7 AI financial assistant, query financial data via natural language, and get professional advice.',
    'cta.title': 'Start Your AI Financial Journey',
    'cta.description': 'Sign up now to experience the convenience and peace of mind of intelligent financial management.',
    'cta.button': 'Start for Free',
    'cta.contact': 'Contact Us',
    'footer.copyright': '© 2025 FinleyBook. All rights reserved.',
    'footer.slogan': 'Smart financial management, making finance simple.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.about': 'About Us',
    'countries.CN': 'China',
    'countries.US': 'United States',
    'countries.AU': 'Australia',
    'countries.GB': 'United Kingdom',
    'countries.JP': 'Japan',
    'countries.CA': 'Canada',
    'countries.EU': 'Europe',

    // Goals
    'goals.title': 'Goal Management',
    'goals.description': 'Set and track your financial goals',
    'goals.totalGoals': 'Total Goals',
    'goals.inProgress': 'In Progress',
    'goals.completed': 'Completed',
    'goals.completionRate': 'Completion Rate',
    'goals.addGoal': 'Add Goal',
    'goals.activeGoals': 'Active Goals',
    'goals.completedGoals': 'Completed Goals',
    'goals.addModal.title': 'Add Goal',
    'goals.editModal.title': 'Edit Goal',
    'goals.name': 'Goal Name',
    'goals.namePlaceholder': 'e.g.: Emergency Fund',
    'goals.descriptionLabel': 'Description (Optional)',
    'goals.descriptionPlaceholder': 'Detailed description of the goal',
    'goals.targetAmount': 'Target Amount',
    'goals.deadline': 'Deadline',
    'goals.category': 'Category',
    'goals.categories.savings': 'Savings Goal',
    'goals.categories.investment': 'Investment Goal',
    'goals.categories.purchase': 'Purchase Goal',
    'goals.categories.debt': 'Debt Repayment',
    'goals.categories.emergency': 'Emergency Fund',
    'goals.update': 'Update',
    'goals.add': 'Add',
    'goals.updateProgress': 'Update Progress',
    'goals.addAmount': 'Add Amount',
    'goals.currentProgress': 'Current progress',
    'goals.daysLeft': 'days left',
    'goals.expired': 'Expired',
    'goals.completedText': 'completed',
    'goals.need': 'Need',
    'goals.congratulations': '🎉 Congratulations! Goal completed!',
    'goals.progressUpdated': 'Progress updated successfully',
    'goals.goalAdded': 'Goal added successfully',
    'goals.goalUpdated': 'Goal updated successfully',
    'goals.goalDeleted': 'Goal deleted successfully',
    'goals.loadError': 'Failed to load goals',
    'goals.fillRequired': 'Please fill in required information',
    'goals.validAmount': 'Please enter a valid amount',

    // Budget
    'budget.title': 'Budget Management',
    'budget.description': 'Set and manage your monthly budget',
    'budget.edit': 'Edit Budget',
    'budget.update': 'Update',
    'budget.loadError': 'Failed to load budgets',
    'budget.used': 'Used',
    'budget.totalBudget': 'Total Budget',
    'budget.spent': 'Spent',
    'budget.remainingBudget': 'Remaining Budget',
    'budget.addBudget': 'Add Budget',
    'budget.category': 'Category',
    'budget.selectCategory': 'Select category',
    'budget.budgetAmount': 'Budget Amount',
    'budget.period': 'Period',
    'budget.monthly': 'Monthly',
    'budget.yearly': 'Yearly',
    'budget.spentAmount': 'Spent ¥{amount}',
    'budget.budgetLimit': 'Budget ¥{amount}',
    'budget.usedPercentage': '% used',
    'budget.remaining': 'Remaining: ',
    'budget.addSuccess': 'Budget added successfully',
    'budget.updateSuccess': 'Budget updated successfully',
    'budget.deleteSuccess': 'Budget deleted successfully',
    'budget.fillComplete': 'Please fill in complete information',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.all': 'All',
    'common.income': 'Income',
    'common.expense': 'Expense',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.earlier': 'Earlier',
    'common.thisWeek': 'This Week',
    'common.thisMonth': 'This Month',
    'common.thisYear': 'This Year',
    'common.allTypes': 'All Types',
    'common.sortByDate': 'Sort by Date',
    'common.sortByAmount': 'Sort by Amount',
    'common.errorLoading': 'Error loading data',

    // Wealth Vault
    'wealth.title': 'Wealth Vault',
    'wealth.myWallet': 'My Wallet',
    'wealth.searchPlaceholder': 'Search brands (e.g. Nike, Apple, Sephora)...',
    'wealth.category.tech': 'Tech',
    'wealth.category.fashion': 'Fashion',
    'wealth.category.travel': 'Travel',
    'wealth.category.food': 'Food',
    'wealth.boost.title': "Today's Boost",
    'wealth.boost.endsIn': 'Ends in',
    'wealth.boost.cashback': 'Cashback',
    'wealth.recommendation.title': 'Based on your Budget',
    'wealth.recommendation.desc': 'You have <span class="font-bold">{amount}</span> left in your <span class="font-bold">{category}</span> budget.',
    'wealth.recommendation.action': 'Buy at <span class="font-bold">{merchant}</span> today to save <span class="font-bold">{saveAmount}</span>.',
    'wealth.recommendation.shopNow': 'Shop Now',
    'wealth.tab.allStores': 'All Stores',
    'wealth.tab.bounties': 'Bank Bounties',
    'wealth.tab.glitch': 'Glitch Hunter',
    'wealth.proTip.title': 'Pro Tip: 100% Commission',
    'wealth.proTip.desc': 'Free users get baseline insights. Pro users unlock deeper diagnostics and faster execution workflows.',
    'wealth.proTip.upgrade': 'Upgrade now',
    'wealth.loading': 'Loading merchants...',
    'wealth.noResults': 'No merchants found matching "{query}"',
    'wealth.claim': 'Claim',
    'wealth.glitch.title': 'Price Glitch Hunter',
    'wealth.glitch.desc': 'These deals expire in minutes. Pro users get instant push notifications.',
    'wealth.glitch.proExclusive': 'Pro Exclusive Glitch',
    'wealth.glitch.upgradeDesc': 'Upgrade to see this 80% off deal',
    'wealth.glitch.unlock': 'Unlock Now',
    'wealth.glitch.live': 'LIVE NOW',
    'wealth.buy': 'Buy',
    'wealth.search': 'Search',
    'wealth.tab.wishlist': 'Wishlist',

    // Wallet Page
    'wallet.proBanner.title': 'Pro Users Earn 2x Faster',
    'wallet.proBanner.desc': 'Upgrade now to unlock faster execution workflows and advanced diagnostics.',
    'wallet.proBanner.cta': 'Upgrade Now',
    'wallet.earned.title': "You've Earned",
    'wallet.earned.desc': 'Shop more to earn <span class="font-bold text-green-600">{amount}</span> to reach payout!',
    'wallet.cashOut.title': 'Cash Out Now',
    'wallet.withdraw': 'Withdraw Funds',
    'wallet.withdraw.info': 'Min $0.01 • Instant to PayPal/Bank',
    'wallet.pending.title': 'On the way',
    'wallet.pending.est': 'Est. Arrival',
    'wallet.totalEarned.title': 'Total Earned',
    'wallet.totalEarned.proTip': '<span class="font-bold text-white">Pro Tip:</span> Upgrade to Pro to earn 2x faster on your next purchase.',
    'wallet.payout.title': 'Payout Settings',
    'wallet.stripe.title': 'Stripe Connect',
    'wallet.stripe.desc': 'Receive payouts directly to your bank account via Stripe.',
    'wallet.stripe.connect': 'Connect / Manage',
    'wallet.history.title': 'Transaction History',
    'wallet.empty.title': 'Start Your Wealth Journey',
    'wallet.empty.desc': "No wallet activity yet. Start from Transactions and Reports to build your first month of financial momentum.",
    'wallet.empty.cta': 'Go to Wealth Vault',
    'wallet.loading': 'Loading wallet...',
    'wallet.withdraw.soon': 'Withdrawal feature coming soon!',

    // Reports Page
    'reports.title': 'Financial Reports',
    'reports.subtitle': 'Professional financial analysis and trend insights',
    'reports.print': 'Print / Save as PDF',
    'reports.downloadPDF': 'Download PDF',
    'reports.exportCSV': 'Export CSV',
    'reports.timeRange.currentMonth': 'This Month',
    'reports.timeRange.lastMonth': 'Last Month',
    'reports.timeRange.currentYear': 'This Year',
    'reports.timeRange.custom': 'Custom Range',
    'reports.summary.totalIncome': 'Total Income',
    'reports.summary.totalExpenses': 'Total Expenses',
    'reports.summary.netIncome': 'Net Income',
    'reports.summary.transactionCount': 'Transactions',
    'reports.summary.dailyAverage': 'Daily Avg',
    'reports.summary.savingsRate': 'Savings Rate',
    'reports.summary.days': 'Days',
    'reports.charts.incomeBreakdown': 'Income Breakdown',
    'reports.charts.expenseBreakdown': 'Expense Breakdown',
    'reports.charts.paymentMethods': 'Payment Methods',
    'reports.charts.trend': 'Income vs Expense Trend',
    'reports.empty.income': 'No income data',
    'reports.empty.expense': 'No expense data',
    'reports.empty.payment': 'No payment data',
    'reports.generatedBy': 'Generated by FinleyBook - Your AI Finance Assistant',

    // Profile Page
    'profile.title': 'My Profile',
    'profile.backDashboard': 'Back to Dashboard',
    'profile.user': 'User',
    'profile.email': 'Email',
    'profile.edit': 'Edit Profile & Settings',
    'profile.joined': 'Joined {date}',
    'profile.stats.savings': 'Lifetime Savings',
    'profile.stats.transactions': 'Transactions',
    'profile.stats.level': 'Current Level',
    'profile.badges.title': 'Achievements',
    'profile.badges.firstCashback': 'First Cashback',
    'profile.badges.budgetMaster': 'Budget Master',
    'profile.badges.wealthPro': 'Wealth Vault Pro',
    'profile.wallet.title': 'Finley Wallet',
    'profile.wallet.balance': 'Balance',
    'profile.wallet.withdraw': 'Withdraw',
    'profile.referral.title': 'Referral Hub',
    'profile.referral.desc': 'Invite friends and unlock Pro collaboration benefits',
    'profile.referral.copy': 'Copy Link',
    'profile.referral.share': 'Share',
    'profile.referral.copied': 'Copied!',
    'profile.referral.progress': '{current}/{total} Friends Invited',
    'profile.referral.unlock': 'Invite {remaining} more to unlock Pro forever',
    'profile.redeem.title': 'Redeem Invite Code',
    'profile.redeem.desc': 'Enter a code from a friend to get 30 days Pro',
    'profile.redeem.placeholder': 'Enter code (e.g. dIlQc6MI)',
    'profile.redeem.button': 'Redeem',
    'profile.redeem.failed': 'Redemption failed',
    'profile.subscription.title': 'Subscription',
    'profile.subscription.desc': 'Manage your subscription plan',

    // Settings
    'settings.title': 'Settings',
    'settings.backDashboard': 'Back to Dashboard',
    'settings.tabs.general': 'General',
    'settings.tabs.notifications': 'Notifications',
    'settings.tabs.security': 'Security',
    'settings.tabs.subscription': 'Subscription',
    'settings.profile': 'Profile',
    'settings.displayName': 'Display Name',
    'settings.preferences': 'Preferences',
    'settings.language': 'Language',
    'settings.country': 'Country & Currency',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.success': 'Settings saved successfully',
    'settings.error': 'Failed to save settings',
    'settings.notifications': 'Notifications',
    'settings.notifications.email': 'Email Notifications',
    'settings.notifications.weeklyReport': 'Weekly Financial Report',
    'settings.notifications.cashback': 'Opportunity Alerts',
    'settings.notifications.updates': 'Product Updates',
    'settings.notifications.push': 'Push Notifications',
    'settings.notifications.budgetWarning': 'Budget Warning',
    'settings.security.password': 'Password',
    'settings.security.changePassword': 'Change Password',
    'settings.security.data': 'Data Management',
    'settings.security.export': 'Export My Data (CSV)',
    'settings.security.delete': 'Delete Account',
    'settings.security.deleteWarning': 'Once you delete your account, there is no going back. Please be certain.',
    'settings.security.dangerZone': 'Danger Zone',
    'settings.security.twoFactor': 'Two-Factor Authentication',
    'settings.security.twoFactorDesc': 'Add an extra layer of security to your account.',
    'settings.security.enable': 'Enable',
    'settings.subscription.plan': 'Current Plan',
    'settings.subscription.upgrade': 'Upgrade to Pro',
    'settings.subscription.manage': 'Manage Subscription',
    'settings.about': 'About',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.clear': 'Clear all',
    'notifications.empty': 'No new notifications',
    'notifications.budgetNudge.title': 'Set up your budget 📉',
    'notifications.budgetNudge.body': 'You are flying blind! Set a monthly limit to unlock savings insights.',

    // Subscription Page
    'subscription.limitedTime': '🔥 Limited Time Offer',
    'subscription.title': 'Not Just Saving, Start Growing Your Wealth',
    'subscription.subtitle': 'Get clear weekly execution plans, unlimited AI diagnostics, and professional reporting workflows for a simple monthly fee.',
    'subscription.subtitle.highlight': '',
    'subscription.averageSavings': 'Average User Savings',
    'subscription.savingsAmount': '$450+ / year',
    'subscription.savingsDesc': 'Via AI Alternative Finder + Desire Cooling',
    'subscription.monthly': 'Monthly',
    'subscription.yearly': 'Yearly',
    'subscription.yearlyDiscount': 'SAVE 33%',
    'subscription.monthlyMsg': '☕️ Less than a coffee a month',
    'subscription.yearlyMsg': '💰 Best Value: $6.67/mo',
    'subscription.bestValue': '⭐ MOST POPULAR',
    'subscription.perMonth': '/ month',
    'subscription.save': 'Save',
    'subscription.startSaving': 'Upgrade Now & Unlock Full Intelligence',
    'subscription.processing': 'Processing...',
    'subscription.guarantee.7day': '✅ 7-day money-back guarantee',
    'subscription.guarantee.cancel': '✅ Cancel anytime in 1-click',
    'subscription.guarantee.hidden': '✅ No hidden fees',
    'subscription.whatYouGet': 'Why Upgrade?',
    'subscription.faq': 'FAQ',

    // Comparison Table
    'subscription.compare.title': 'Free vs Pro Plan',
    'subscription.compare.feature': 'Feature',
    'subscription.compare.free': 'Free',
    'subscription.compare.pro': 'Pro',
    'subscription.compare.cashback': 'Execution Automation',
    'subscription.compare.cashback.free': 'Manual',
    'subscription.compare.cashback.pro': 'AI-assisted + one-click apply',
    'subscription.compare.withdraw': 'Withdrawal Limit',
    'subscription.compare.withdraw.free': '$50/mo (Slow)',
    'subscription.compare.withdraw.pro': '$500/mo (Instant)',
    'subscription.compare.ai': 'AI Price Finder',
    'subscription.compare.ai.free': 'Daily Limit',
    'subscription.compare.ai.pro': 'Unlimited + Instant',
    'subscription.compare.wishlist': 'Wishlist Tracking',
    'subscription.compare.wishlist.free': 'Manual',
    'subscription.compare.wishlist.pro': 'Auto-Monitor + Price Drop Alerts',
    'subscription.compare.privacy': 'Privacy Mode',
    'subscription.compare.privacy.free': 'Basic',
    'subscription.compare.privacy.pro': 'Camouflage Mode (Anti-snoop)',
    'subscription.compare.support': 'Support',
    'subscription.compare.support.free': 'Email (48h)',
    'subscription.compare.support.pro': 'Live Chat (Priority)',

    // Testimonials
    'subscription.testimonials.title': 'What Users Are Saying',
    'subscription.testimonial.1.text': 'I never thought I could make money by shopping! Now I withdraw every month, it feels like free money.',
    'subscription.testimonial.1.author': 'Sarah J.',
    'subscription.testimonial.2.text': 'The AI Finder saved me $120 on a single purchase. The subscription paid for itself instantly.',
    'subscription.testimonial.2.author': 'Mike T.',
    'subscription.testimonial.3.text': 'I love the "Desire Cooling" feature. It stopped me from buying so much useless stuff.',
    'subscription.testimonial.3.author': 'Emily R.',

    // Features
    'subscription.features.icloud.title': 'iCloud Encrypted Backup',
    'subscription.features.icloud.desc': 'Zero-knowledge encryption (Data safe when switching phones)',
    'subscription.features.widget.title': 'Lock Screen Widget',
    'subscription.features.widget.desc': 'Record expenses without opening app',
    'subscription.features.lifehour.title': 'Life-Hour Calculator',
    'subscription.features.lifehour.desc': 'Convert prices to work hours (See the real cost)',
    'subscription.features.ai.title': 'AI Alternative Finder',
    'subscription.features.ai.desc': 'Paste product link, get cheaper options',
    'subscription.features.camo.title': 'Camouflage Mode',
    'subscription.features.camo.desc': 'Shake to hide as calculator',
    'subscription.features.wishlist.title': 'Unlimited Wishlist',
    'subscription.features.wishlist.desc': 'Desire cooling + price tracking',
    'subscription.features.cashback.title': 'AI Workflow Automation',
    'subscription.features.cashback.desc': 'Convert recommendations into transactions, budgets, and goals with confirmation',

    // Subscription Status
    'subscription.status.free': 'Free Plan',
    'subscription.status.pro': 'Pro Member',
    'subscription.status.current': 'Current Plan',
    'subscription.status.upgrade': 'Upgrade to Pro',
    'subscription.status.renew': 'Renews on: {date}',
    'subscription.status.cancel': 'Cancel Subscription',
    'subscription.status.free.desc': 'Basic features for daily tracking',
    'subscription.status.pro.desc': 'Unlock all premium features',
    'subscription.features.free.limit': 'Monthly Transactions: 50',
    'subscription.features.free.categories': 'Budget Categories: 5',
    'subscription.features.free.export': 'Data Export: 2/month',
    'subscription.features.pro.unlimited': 'Unlimited Tracking • AI Analysis',
    'subscription.unlock': 'Unlock unlimited features & boost efficiency',

    // Leveling
    'level.tooltip.title': 'How to Level Up',
    'level.tooltip.desc': 'Invite friends to upgrade your level. Higher levels unlock advanced badges and collaboration perks.',
    'level.tooltip.next': 'Next Level: Invite {count} more friends',

    // Error Boundary
    'error.title': 'Oops, something went wrong',
    'error.desc': 'The app encountered an unexpected error. Your data is safe. Please try refreshing the page.',
    'error.refresh': 'Refresh Page',
    'error.details': 'View Error Details (Dev)',

    // Wallet - New Additions
    'wallet.status.level.gold': 'Gold Saver',
    'wallet.status.level.silver': 'Silver Saver',
    'wallet.status.level.bronze': 'Bronze Saver',
    'wallet.status.keepEarning': 'Keep earning to level up!',
    'wallet.stripe.connecting': 'Connecting to Stripe...',
    'wallet.stripe.redirecting': 'Redirecting to Stripe...',
    'wallet.stripe.error': 'Failed to connect Stripe account',
    'wallet.withdraw.success': 'Withdrawal initiated! Funds are on the way.',
    'wallet.withdraw.minAmount': 'You need at least $0.01 to withdraw.',
    'wallet.pending.status.pending': 'Pending',
    'wallet.pending.status.approved': 'Approved',
    'wallet.pending.status.ready': 'Ready',

    // Wealth - New Additions
    'wealth.tooltip.howItWorks.title': 'How Cashback Works',
    'wealth.tooltip.howItWorks.desc': 'We track your click to the merchant. When you make a purchase, the merchant notifies us (usually within 3-5 days), and we credit your wallet.',
    'wealth.search.recent': 'Recent Searches',
    'wealth.search.clear': 'Clear',
    'wealth.section.featured': 'Featured Products',
    'wealth.section.matching': 'Matching Stores',
    'wealth.section.trending': 'Trending Stores',
    'wealth.noResults.tip': 'Try searching for broader terms like "Tech" or "Shoes"',

    // Landing Page
    'landing.hero.demo.guest': 'Try Demo (Guest)',
    'landing.hero.demo.viz.totalBalance': 'Total Balance',
    'landing.hero.demo.viz.monthlyBudget': 'Monthly Budget',
    'landing.demo.title': 'Experience the Power',
    'landing.demo.subtitle': 'See how FinleyBook transforms your financial data.',
    'landing.demo.viz.totalAssets': 'Total Assets',
    'landing.demo.viz.income': 'Income',
    'landing.demo.viz.expense': 'Expense',
    'landing.footer.pricing': 'Pricing',
    'landing.footer.blog': 'Blog',
    'landing.footer.about': 'About',

    'landing.stats.trusted': 'Trusted by Users',
    'landing.stats.desc': 'Join thousands of users on their journey to financial intelligence.',
    'landing.stats.users': 'Active Users',
    'landing.stats.assets': 'Assets Managed',
    'landing.stats.reviews': 'User Rating',

    // Insights
    'insights.title': 'AI Insights',
    'insights.viewAll': 'View All',
    'insights.highPriority': 'High Priority',
    'insights.mediumPriority': 'Medium Priority',
    'insights.lowPriority': 'Low Priority',
    'insights.viewAdvice': 'View Advice',
    'insights.noInsights': 'No new insights',
    'insights.analyzing': 'AI is analyzing your financial data, personalized advice coming soon.',

  },
  zh: {
    // Navigation & General
    'nav.dashboard': '财务概览',
    'nav.transactions': '交易记录',
    'referral.title': '邀请好友',
    'referral.subtitle': '获取免费 Pro 会员',
    'referral.share_button': '分享邀请链接',
    'referral.stats_title': '我的邀请',
    'referral.viral_share_wechat': '我用 FinleyBook 省了快 ¥900，送你 30 天 Pro 随便用！[链接]',
    'referral.viral_share_whatsapp': 'This app saved me ¥900 last month - 30 days Pro free for you! [link]',
    'nav.budget': '预算管理',
    'nav.goals': '理财目标',
    'nav.reports': '报表分析',
    'reports.downloadPDF': '下载 PDF',
    'nav.settings': '设置',
    'nav.profile': '个人资料',
    'nav.subscription': '订阅管理',
    'nav.about': '关于我们',
    'nav.blog': '博客',
    'nav.terms': '服务条款',
    'nav.privacy': '隐私政策',
    'nav.signOut': '退出登录',
    'nav.rewards': '洞察中心',
    'nav.searchPlaceholder': '搜索财富、产品...',
    'nav.me': '我的',
    'wealth.search': '搜索',
    'wealth.tab.wishlist': '心愿单',

    // Dashboard
    'dashboard.title': '财务概览',
    'dashboard.date': '{date}',
    'dashboard.totalAssets': '总资产',
    'dashboard.monthlyIncome': '本月收入',
    'dashboard.monthlyExpenses': '本月支出',
    'dashboard.savingsRate': '储蓄率',
    'dashboard.cumulativeNetAssets': '累计净资产',
    'dashboard.monthlyTotalExpenses': '本月总支出',
    'dashboard.monthlySavingsRatio': '本月储蓄占比',
    'dashboard.totalIncome': '总收入',
    'dashboard.totalExpenses': '总支出',
    'dashboard.netIncome': '净收入',
    'dashboard.welcomeBack': '欢迎回来，{name}！',
    'dashboard.wealthCommandCenter': '您的财富指挥中心',
    'dashboard.proAd.title': '升级到 Pro 版',
    'dashboard.proAd.desc': '解锁无限交易记录、AI 智能分析和自定义分类。',
    'dashboard.profitOrb.label': '本月已赚',
    'dashboard.profitOrb.sublabel': '利润中心',

    // Charts
    'charts.expenseBreakdown': '支出分类占比',
    'charts.incomeVsExpense': '收支对比',
    'charts.income': '收入',
    'charts.expense': '支出',
    'charts.amount': '金额',
    'charts.noData': '暂无交易数据，无法生成图表',

    // Recent Transactions
    'transactions.recent': '最近交易',
    'transactions.addTransaction': '添加交易',
    'transactions.noRecords': '暂无交易记录',
    'transactions.startAdding': '开始添加您的第一笔交易',
    'transactions.showMore': '查看更多交易',
    'transactions.showLess': '显示最近10条',
    'transactions.subtitle': '管理您的收入和支出记录',
    'transactions.noResults': '没有找到匹配的交易记录',
    'transactions.title': '交易记录',
    'transactions.add': '添加交易',

    // Transaction Modal
    'transaction.add': '添加交易记录',
    'transaction.type': '交易类型',
    'transaction.income': '💰 收入',
    'transaction.expense': '💸 支出',
    'transaction.amount': '金额 *',
    'transaction.category': '分类 *',
    'transaction.selectCategory': '选择分类',
    'transaction.description': '描述 *',
    'transaction.descriptionPlaceholder': '交易描述',
    'transaction.date': '日期',
    'transaction.paymentMethod': '支付方式',
    'transaction.cancel': '取消',
    'transaction.submit': '添加交易',
    'transaction.submitting': '添加中...',
    'transaction.success': '交易添加成功！',
    'transaction.successMessage': '交易记录添加成功',
    'transaction.error': '添加交易记录失败',

    // Payment Methods
    'payment.cash': '现金',
    'payment.bankCard': '银行卡',
    'payment.alipay': '支付宝',
    'payment.wechat': '微信支付',
    'payment.creditCard': '信用卡',
    'payment.other': '其他',

    // Categories - Income
    'category.salary': '工资收入',
    'category.investment': '投资收益',
    'category.parttime': '兼职收入',
    'category.otherIncome': '其他收入',

    // Categories - Expense
    'category.food': '餐饮美食',
    'category.transport': '交通出行',
    'category.shopping': '购物消费',
    'category.housing': '居住缴费',
    'category.health': '医疗健康',
    'category.entertainment': '文化娱乐',
    'category.education': '学习教育',
    'category.otherExpense': '其他支出',

    // Quick Actions
    'quickActions.title': '快速操作',
    'quickActions.subtitle': '选择一个操作开始',
    'quickActions.addTransaction': '添加交易',
    'quickActions.addTransactionDesc': '手动记录收入或支出',
    'quickActions.scanReceipt': '扫描票据',
    'quickActions.scanReceiptDesc': '拍照自动识别',
    'quickActions.voiceInput': '语音记账',
    'quickActions.voiceInputDesc': '说话快速记录',
    'quickActions.viewTransactions': '查看账单',
    'quickActions.viewTransactionsDesc': '浏览交易明细',
    'quickActions.inviteFriend': '邀请好友',
    'quickActions.inviteFriendDesc': '送 Pro 会员',

    // Wallet - New Additions
    'wallet.status.level.gold': '金牌储蓄家',
    'wallet.status.level.silver': '银牌储蓄家',
    'wallet.status.level.bronze': '铜牌储蓄家',
    'wallet.status.keepEarning': '继续赚取返利以升级！',
    'wallet.stripe.connecting': '正在连接 Stripe...',
    'wallet.stripe.redirecting': '正在跳转至 Stripe...',
    'wallet.stripe.error': '连接 Stripe 账户失败',
    'wallet.withdraw.success': '提现已发起！资金正在路上。',
    'wallet.withdraw.minAmount': '提现金额至少需要 $0.01。',
    'wallet.pending.status.pending': '处理中',
    'wallet.pending.status.approved': '已批准',
    'wallet.pending.status.ready': '可提现',

    // Wealth - New Additions
    'wealth.tooltip.howItWorks.title': '返利如何运作',
    'wealth.tooltip.howItWorks.desc': '我们会追踪您到商家的点击。当您完成购买后，商家会通知我们（通常在 3-5 天内），我们会将返利存入您的钱包。',
    'wealth.search.recent': '最近搜索',
    'wealth.search.clear': '清除',
    'wealth.section.featured': '精选商品',
    'wealth.section.matching': '匹配商家',
    'wealth.section.trending': '热门商家',
    'wealth.noResults.tip': '尝试搜索更广泛的关键词，如“科技”或“鞋子”',

    // Landing Page
    'landing.hero.demo.guest': '体验演示 (游客)',
    'landing.hero.demo.viz.totalBalance': '总余额',
    'landing.hero.demo.viz.monthlyBudget': '月度预算',
    'landing.demo.title': '体验强大功能',
    'landing.demo.subtitle': '看看 FinleyBook 如何改变您的财务管理方式。',
    'landing.demo.viz.totalAssets': '总资产',
    'landing.demo.viz.income': '收入',
    'landing.demo.viz.expense': '支出',
    'landing.footer.pricing': '定价',
    'landing.footer.blog': '博客',
    'landing.footer.about': '关于我们',

    'landing.stats.trusted': '深受用户信赖',
    'landing.stats.desc': '加入数万名用户的行列，开始您的智能财务之旅',
    'landing.stats.users': '活跃用户',
    'landing.stats.assets': '管理资产',
    'landing.stats.reviews': '用户好评',

    // Budget
    'budget.overBudget': '超支 {amount}',
    'budget.emptyTitle': '暂无预算',
    'budget.emptyDesc': '设置每月支出上限，轻松实现储蓄目标。',
    'budget.createFirst': '创建第一个预算',

    // Auth
    'auth.welcomeBack': '欢迎回来',
    'auth.createAccount': '创建账户',
    'auth.signIn': '登录',

    // Error Boundary
    'error.title': '哎呀，出现了问题',
    'error.desc': '应用遇到了意外错误，别担心，您的数据是安全的。请尝试刷新页面重试。',
    'error.refresh': '刷新页面',
    'error.details': '查看错误详情 (开发模式)',
    'auth.signUp': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.signInDescription': '登录以继续使用您的智能财务助手',
    'auth.signUpDescription': '开始您的智能财务管理之旅',
    'auth.googleSignIn': '使用 Google 登录',
    'auth.continueEmail': '使用邮箱继续',
    'auth.signup': '注册',
    'auth.login': '登录',
    'auth.haveAccount': '已有账号？',
    'auth.noAccount': '没有账号？',
    'auth.or': '或',
    'auth.forgotPassword': '忘记密码？',
    'auth.emailPlaceholder': '请输入您的邮箱',
    'auth.passwordPlaceholder': '请输入密码',
    'auth.passwordSignUpPlaceholder': '至少6位字符',
    'auth.confirmPasswordPlaceholder': '请再次输入密码',
    'auth.processing': '处理中...',
    'auth.signInSuccess': '登录成功!',
    'auth.signUpSuccess': '注册成功!',
    'auth.googleSignInSuccess': 'Google登录成功!',
    'auth.signInError': '登录失败，请检查邮箱和密码',
    'auth.signUpError': '注册失败，请稍后重试',
    'auth.googleSignInError': 'Google登录失败',
    'auth.enterEmailFirst': '请先输入您的邮箱',
    'auth.passwordResetSent': '密码重置邮件已发送！请查看您的邮箱。',
    'auth.passwordResetError': '发送密码重置邮件失败',

    // Form Validation
    'validation.emailRequired': '请输入邮箱地址',
    'validation.emailInvalid': '请输入有效的邮箱地址',
    'validation.passwordRequired': '请输入密码',
    'validation.passwordTooShort': '密码至少需要6位字符',
    'validation.confirmPasswordRequired': '请确认密码',
    'validation.passwordMismatch': '两次输入的密码不一致',
    'validation.amountRequired': '请输入有效的金额',
    'validation.categoryRequired': '请选择交易分类',
    'validation.descriptionRequired': '请输入交易描述',
    'validation.dateRequired': '请选择交易日期',

    // Landing Page
    'landing.title': 'AI智能财务管理',
    'landing.subtitle': '通过智能洞察、自动追踪和个性化建议，掌控您的财务状况',
    'landing.getStarted': '免费开始',
    'landing.learnMore': '了解更多',
    'landing.features.tracking': '智能追踪',
    'landing.features.insights': 'AI洞察',
    'landing.features.budgeting': '智能预算',
    'landing.features.security': '银行级安全',

    // Onboarding Guide
    'guide.title': '快速开始',
    'guide.step.transaction.title': '添加第一笔交易',
    'guide.step.transaction.desc': '记录您的第一笔收入或支出',
    'guide.step.transaction.action': '立即添加',
    'guide.step.export.title': '导出数据',
    'guide.step.export.desc': '将财务报表导出为 PDF 或 CSV',
    'guide.step.export.action': '前往报表',
    'guide.step.cashback.title': '每周复盘',
    'guide.step.cashback.desc': '复盘支出并执行一个优化动作',
    'guide.step.cashback.action': '前往报表',
    'guide.step.profile.title': '完善资料',
    'guide.step.profile.desc': '设置您的偏好和理财目标',
    'guide.step.profile.action': '前往设置',
    'guide.progress': '已完成 {current}/{total}',
    'guide.dismiss': '关闭指南',

    // New Landing Page (Financial Navigator)
    'landing.badge': '理财，游戏化',
    'landing.hero.title.prefix': '省钱。',
    'landing.hero.title.highlight': '返现。积累财富。',
    'landing.hero.desc': '第一个会给你钱的记账软件。完成简单任务，聪明消费，看着存款自动增长。',
    'landing.cta.start': '立即开始省钱',
    'landing.hero.sub': '银行级安全 · 无需信用卡',
    'landing.features.badge': '为什么选择 FinleyBook',
    'landing.features.title': '智能返利 & 追踪',
    'landing.features.desc': '体验未来的个人财务管理。我们帮你在消费中省钱。',
    'landing.feature.safe.title': '今日可花 (Safe-to-Spend)',
    'landing.feature.safe.desc': '一眼看懂今天还能花多少钱。绿色安全，红色警示。',
    'landing.feature.drag.title': '智能返利',
    'landing.feature.drag.desc': '通过 FinleyBook 购物享最高 15% 返利。把订阅费赚回来。',
    'landing.feature.time.title': '时光机预测',
    'landing.feature.time.desc': '看看现在的消费习惯，会让你在 5 年后成为富翁还是穷光蛋。',
    'landing.trust.users': '超过 10,000+ 用户信赖',
    'landing.trust.security': '银行级安全加密',
    'landing.trust.privacy': '100% 隐私保护',
    'landing.calculator.title': '你能赚多少？',
    'landing.calculator.spend': '每月网购金额',
    'landing.calculator.result': '使用 FinleyBook，你可以每月省下 <span class="text-indigo-600 font-bold">{amount}</span> + 保持预算正轨。',

    // Onboarding
    'onboarding.identity.title': '目前的财务状态？',
    'onboarding.identity.survival.title': '月光族生存模式',
    'onboarding.identity.survival.desc': '工资刚到账就没了',
    'onboarding.identity.shopaholic.title': '这就去买买买',
    'onboarding.identity.shopaholic.desc': '控制不住剁手',
    'onboarding.identity.saver.title': '正在存钱买大件',
    'onboarding.identity.saver.desc': '为了梦想而奋斗',
    'onboarding.pain.title': '说实话...',
    'onboarding.pain.desc': '你觉得每个月有多少钱是“不知道花哪去了”？',
    'onboarding.pain.min': '$50 (小意思)',
    'onboarding.pain.max': '$500+ (救命!)',
    'onboarding.pain.annual': '这相当于你每年扔掉了',
    'onboarding.pain.next': '下一步',
    'onboarding.dream.title': '如果我们能帮你找回这笔钱...',
    'onboarding.dream.desc': '明年这个时候，你可以拥有：',
    'onboarding.dream.ipad': '一台 iPad Air',
    'onboarding.dream.flight': '一张回国往返机票',
    'onboarding.dream.rent': '三个月的房租',
    'onboarding.dream.value': '价值约 ${amount}',
    'onboarding.dream.cta': '带我去找回这笔钱',
    'onboarding.final.title': '最后一步',
    'onboarding.final.desc': '只需一秒，开启你的“机票基金”账户。',
    'onboarding.final.google': '使用 Google 开启',
    'onboarding.final.terms': '点击即代表同意我们的服务条款',



    // Language Settings
    'language.title': '语言设置',
    'language.description': '选择您首选的界面语言',
    'language.english': 'English (英语)',
    'language.chinese': '简体中文',
    'language.current': '当前语言',
    'language.save': '保存更改',
    'language.saved': '语言偏好已保存',

    // Landing Page Legacy (for backward compatibility)
    'nav.login': '登录',
    'nav.register': '免费注册',
    'nav.features': '功能',
    'nav.pricing': '价格',
    'hero.title_prefix': 'AI驱动的',
    'hero.title_highlight': '个人财务',
    'hero.title_suffix': '管理平台',
    'hero.description': '集智能记账、财务分析、税务管理于一体的AI财务助手。让复杂的财务管理变得简单智能，助您实现财务自由。',
    'hero.start': '开始使用',
    'hero.learn_more': '了解更多',
    'features.title': '智能财务管理',
    'features.subtitle': '核心功能矩阵',
    'features.description': '围绕"数据归集、智能分析、风险预警、个性化服务"四大主线，提供超越传统记账软件的深度价值。',
    'features.items.aggregation.title': '智能数据归集',
    'features.items.aggregation.desc': '自动聚合银行账户、支付平台数据，OCR识别票据信息，支持自然语言记账',
    'features.items.analysis.title': '智能分析预测',
    'features.items.analysis.desc': '基于AI的个性化财务分析，现金流预测，智能预算建议',
    'features.items.tax.title': '税务风险预警',
    'features.items.tax.desc': '实时监测税务合规风险，发票验真，重复报销检测，政策变动提醒',
    'features.items.ai.title': 'AI智能问答',
    'features.items.ai.desc': '24/7 AI财务助手，自然语言查询财务数据，获取专业建议',
    'cta.title': '开启您的AI财务管理之旅',
    'cta.description': '立即注册，体验智能化财务管理带来的便捷与安心。',
    'cta.button': '免费开始',
    'cta.contact': '联系我们',
    'footer.copyright': '© 2025 FinleyBook. 保留所有权利。',
    'footer.slogan': '智能财务管理，让理财更简单',
    'footer.privacy': '隐私政策',
    'footer.terms': '使用条款',
    'footer.about': '关于我们',
    'countries.CN': '中国',
    'countries.US': '美国',
    'countries.AU': '澳大利亚',
    'countries.GB': '英国',
    'countries.JP': '日本',
    'countries.CA': '加拿大',
    'countries.EU': '欧洲',

    // Goals
    'goals.title': '目标管理',
    'goals.description': '设定并追踪您的财务目标',
    'goals.totalGoals': '总目标',
    'goals.inProgress': '进行中',
    'goals.completed': '已完成',
    'goals.completionRate': '完成率',
    'goals.addGoal': '添加目标',
    'goals.activeGoals': '进行中的目标',
    'goals.completedGoals': '已完成的目标',
    'goals.addModal.title': '添加目标',
    'goals.editModal.title': '编辑目标',
    'goals.name': '目标名称',
    'goals.namePlaceholder': '例如：紧急基金',
    'goals.descriptionLabel': '描述（可选）',
    'goals.descriptionPlaceholder': '目标的详细描述',
    'goals.targetAmount': '目标金额',
    'goals.deadline': '截止日期',
    'goals.category': '分类',
    'goals.categories.savings': '储蓄目标',
    'goals.categories.investment': '投资目标',
    'goals.categories.purchase': '购买目标',
    'goals.categories.debt': '债务清偿',
    'goals.categories.emergency': '应急基金',
    'goals.update': '更新',
    'goals.add': '添加',
    'goals.updateProgress': '更新进度',
    'goals.addAmount': '增加金额',
    'goals.currentProgress': '当前进度',
    'goals.daysLeft': '天后到期',
    'goals.expired': '已过期',
    'goals.completedText': '完成',
    'goals.need': '还需',
    'goals.congratulations': '🎉 恭喜！目标已完成！',
    'goals.progressUpdated': '进度更新成功',
    'goals.goalAdded': '目标添加成功',
    'goals.goalUpdated': '目标更新成功',
    'goals.goalDeleted': '目标删除成功',
    'goals.loadError': '加载目标失败',
    'goals.fillRequired': '请填写必要信息',
    'goals.validAmount': '请输入有效金额',

    // Budget
    'budget.title': '预算管理',
    'budget.description': '设置和管理您的月度预算',
    'budget.edit': '编辑预算',
    'budget.update': '更新',
    'budget.loadError': '加载预算失败',
    'budget.used': '已使用',
    'budget.totalBudget': '总预算',
    'budget.spent': '已花费',
    'budget.remainingBudget': '剩余预算',
    'budget.addBudget': '添加预算',
    'budget.category': '分类',
    'budget.selectCategory': '选择分类',
    'budget.budgetAmount': '预算金额',
    'budget.period': '周期',
    'budget.monthly': '月度',
    'budget.yearly': '年度',
    'budget.spentAmount': '已花费 ¥{amount}',
    'budget.budgetLimit': '预算 ¥{amount}',
    'budget.usedPercentage': '% 已使用',
    'budget.remaining': '剩余: ',
    'budget.addSuccess': '预算添加成功',
    'budget.updateSuccess': '预算更新成功',
    'budget.deleteSuccess': '预算删除成功',
    'budget.fillComplete': '请填写完整信息',

    // Dashboard
    'dashboard.budget.managing': '正在管理您的 {amount} 月度预算',
    'dashboard.budget.setup': '设置预算，开始追踪您的财务之旅',
    'dashboard.wealthVault.title': '财富金库',
    'dashboard.wealthVault.earnings': '总收益',
    'dashboard.wealthVault.earnBack': '赚回 $9.99 订阅费',
    'dashboard.wealthVault.progress': '免费 Pro 进度',
    'dashboard.wealthVault.cta': '前往财富金库',
    'dashboard.ai.title': 'AI 财务分析',
    'dashboard.ai.desc': '升级 Pro 获取个性化 AI 财务建议和深度洞察',
    'dashboard.usage.title': '使用限额',
    'dashboard.usage.transactions': '月度交易',
    'dashboard.usage.budgets': '预算分类',
    'dashboard.health.title': '财务健康分',
    'dashboard.health.noData': '暂无评分数据',
    'dashboard.health.unlock': '添加 7 天交易记录以解锁您的财务健康分',
    'dashboard.cashFlow': '现金流趋势',
    'dashboard.pendingCashback': '待入账返利',
    'dashboard.actionPotential': '可优化金额',
    'dashboard.actionPotentialDescription': '预计每月可提升空间',
    'dashboard.finleyFocusScore': 'Finley 专注得分',
    'dashboard.focusScoreDescription': '当前财务系统就绪度',
    'dashboard.nextMoveSignature': 'Finley 一步引擎™',
    'dashboard.nextMoveImpact': '预计每月影响',
    'dashboard.nextMoveDoNow': '立即执行',
    'dashboard.nextMoveAskAI': '问 AI 为什么',
    'dashboard.nextMoveShare': '分享计划',
    'dashboard.nextMoveCopied': '计划已复制，可直接分享给朋友。',
    'dashboard.nextMoveShareTemplate': '我在 Finley 的下一步策略：{title}。{impact}。你也可以试试：{url}',
    'dashboard.smartSuggestions': '智能建议',
    'dashboard.missedCashback': '你知道吗？你错过了 {amount} 返利。下次记得通过财富金库购物！',
    'dashboard.renewEarn': '续费赚取',
    'dashboard.budget.shopSave': '计划购物？在 {merchant} 可省 {rate}。',
    'charts.others': '其他',
    'common.cancel': '取消',

    'common.edit': '编辑',
    'common.delete': '删除',
    'common.confirm': '确认',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.close': '关闭',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.all': '全部',
    'common.income': '收入',
    'common.expense': '支出',
    'common.yes': '是',
    'common.no': '否',
    'common.today': '今天',
    'common.yesterday': '昨天',
    'common.earlier': '更早',
    'common.thisWeek': '本周',
    'common.thisMonth': '本月',
    'common.thisYear': '今年',
    'common.allTypes': '全部类型',
    'common.sortByDate': '按日期排序',
    'common.errorLoading': '加载数据失败',
    // Profile Page
    'profile.title': '个人主页',
    'profile.backDashboard': '返回仪表盘',
    'profile.user': '用户',
    'profile.email': '邮箱',
    'profile.edit': '编辑资料与设置',
    'profile.joined': '加入时间 {date}',
    'profile.stats.savings': '累计节省',
    'profile.stats.transactions': '交易笔数',
    'profile.stats.level': '当前等级',
    'profile.badges.title': '成就徽章',
    'profile.badges.firstCashback': '首笔返利',
    'profile.badges.budgetMaster': '预算大师',
    'profile.badges.wealthPro': '财富专家',
    'profile.wallet.title': 'Finley 钱包',
    'profile.wallet.balance': '余额',
    'profile.wallet.withdraw': '提现',
    'profile.referral.title': '邀请中心',
    'profile.referral.desc': '邀请好友，解锁 Pro 协作权益',
    'profile.referral.copy': '复制链接',
    'profile.referral.share': '分享',
    'profile.referral.copied': '已复制！',
    'profile.referral.progress': '已邀请 {current}/{total} 位好友',
    'profile.referral.unlock': '再邀请 {remaining} 位即可永久解锁 Pro',
    'profile.redeem.title': '兑换邀请码',
    'profile.redeem.desc': '输入好友的邀请码，领取 30 天 Pro 会员',
    'profile.redeem.placeholder': '输入邀请码 (例如 dIlQc6MI)',
    'profile.redeem.button': '兑换',
    'profile.redeem.failed': '兑换失败',
    'profile.subscription.title': '订阅管理',
    'profile.subscription.desc': '管理您的订阅计划',

    // Settings
    'settings.title': '设置',
    'settings.backDashboard': '返回仪表盘',
    'settings.tabs.general': '常规',
    'settings.tabs.notifications': '通知',
    'settings.tabs.security': '安全',
    'settings.tabs.subscription': '订阅',
    'settings.profile': '个人资料',
    'settings.displayName': '显示名称',
    'settings.preferences': '偏好设置',
    'settings.language': '语言',
    'settings.country': '国家与货币',
    'settings.save': '保存更改',
    'settings.saving': '保存中...',
    'settings.success': '设置已保存',
    'settings.error': '保存失败',
    'settings.notifications.email': '邮件通知',
    'settings.notifications.weeklyReport': '每周财务报告',
    'settings.notifications.cashback': '机会提醒',
    'settings.notifications.updates': '产品更新',
    'settings.notifications.push': '推送通知',
    'settings.notifications.budgetWarning': '预算超支预警',
    'settings.security.password': '密码',
    'settings.security.changePassword': '修改密码',
    'settings.security.data': '数据管理',
    'settings.security.export': '导出数据 (CSV)',
    'settings.security.delete': '删除账户',
    'settings.security.deleteWarning': '一旦删除账号，数据将无法恢复。请谨慎操作。',
    'settings.security.dangerZone': '危险区域',
    'settings.security.twoFactor': '双重验证 (2FA)',
    'settings.security.twoFactorDesc': '为您的账户添加额外的安全保护。',
    'settings.security.enable': '开启',
    'settings.subscription.plan': '当前计划',
    'settings.subscription.upgrade': '升级到 Pro',
    'settings.subscription.manage': '管理订阅',
    'settings.about': '关于我们',

    // Notifications
    'notifications.budgetNudge.title': '设置您的预算 📉',
    'notifications.budgetNudge.body': '您正在盲目消费！设置每月限额以解锁储蓄洞察。',

    // Wealth Vault
    'wealth.title': '财富金库',
    'wealth.myWallet': '我的钱包',
    'wealth.searchPlaceholder': '搜索品牌 (如 Nike, Apple, Sephora)...',
    'wealth.category.tech': '数码',
    'wealth.category.fashion': '时尚',
    'wealth.category.travel': '旅游',
    'wealth.category.food': '美食',
    'wealth.boost.title': '今日加码',
    'wealth.boost.endsIn': '距结束',
    'wealth.boost.cashback': '返利',
    'wealth.recommendation.title': '基于您的预算推荐',
    'wealth.recommendation.desc': '您的 <span class="font-bold">{category}</span> 预算还剩 <span class="font-bold">{amount}</span>。',
    'wealth.recommendation.action': '今天在 <span class="font-bold">{merchant}</span> 购买可省 <span class="font-bold">{saveAmount}</span>。',
    'wealth.recommendation.shopNow': '立即购买',
    'wealth.tab.allStores': '所有商家',
    'wealth.tab.bounties': '银行赏金',
    'wealth.tab.glitch': '漏洞猎人',
    'wealth.proTip.title': 'Pro 提示: 100% 佣金',
    'wealth.proTip.desc': '免费用户获得基础洞察。Pro 用户可解锁更深度诊断与更快执行工作流。',
    'wealth.proTip.upgrade': '立即升级',
    'wealth.loading': '加载商家中...',
    'wealth.noResults': '未找到匹配 "{query}" 的商家',
    'wealth.claim': '领取',
    'wealth.glitch.title': '价格漏洞猎人',
    'wealth.glitch.desc': '这些优惠几分钟内就会失效。Pro 用户可获得即时推送通知。',
    'wealth.glitch.proExclusive': 'Pro 专属漏洞',
    'wealth.glitch.upgradeDesc': '升级以查看此 80% 折扣优惠',
    'wealth.glitch.unlock': '立即解锁',
    'wealth.glitch.live': '进行中',
    'wealth.buy': '购买',

    // Wallet Page
    'wallet.proBanner.title': 'Pro 用户赚钱快 2 倍',
    'wallet.proBanner.desc': '立即升级，解锁更快执行工作流与高级诊断能力。',
    'wallet.proBanner.cta': '立即升级',
    'wallet.earned.title': '您已赚取',
    'wallet.earned.desc': '再赚 <span class="font-bold text-green-600">{amount}</span> 即可提现！',
    'wallet.cashOut.title': '立即提现',
    'wallet.withdraw': '提取资金',
    'wallet.withdraw.info': '最低 $0.01 • 秒到 PayPal/银行卡',
    'wallet.pending.title': '在路上',
    'wallet.pending.est': '预计到账',
    'wallet.totalEarned.title': '累计赚取',
    'wallet.totalEarned.proTip': '<span class="font-bold text-white">Pro 提示:</span> 升级 Pro，下一笔消费赚取 2 倍返利。',
    'wallet.payout.title': '提现设置',
    'wallet.stripe.title': 'Stripe 连接',
    'wallet.stripe.desc': '通过 Stripe 直接提现到您的银行账户。',
    'wallet.stripe.connect': '连接 / 管理',
    'wallet.history.title': '交易记录',
    'wallet.empty.title': '开启您的财富之旅',
    'wallet.empty.desc': '钱包暂无活动记录。先从交易与报表开始，建立第一个月的财务节奏。',
    'wallet.empty.cta': '前往财富金库',
    'wallet.loading': '加载钱包中...',
    'wallet.withdraw.soon': '提现功能即将上线！',

    // Reports Page
    'reports.title': '财务报表',
    'reports.subtitle': '专业级财务分析与趋势洞察',
    'reports.print': '打印 / 导出 PDF',
    'reports.exportCSV': '导出 CSV',
    'reports.timeRange.currentMonth': '本月',
    'reports.timeRange.lastMonth': '上月',
    'reports.timeRange.currentYear': '本年',
    'reports.timeRange.custom': '自定义范围',
    'reports.summary.totalIncome': '总收入',
    'reports.summary.totalExpenses': '总支出',
    'reports.summary.netIncome': '净收入',
    'reports.summary.transactionCount': '交易笔数',
    'reports.summary.dailyAverage': '日均',
    'reports.summary.savingsRate': '储蓄率',
    'reports.summary.days': '统计天数',
    'reports.charts.incomeBreakdown': '收入构成',
    'reports.charts.expenseBreakdown': '支出构成',
    'reports.charts.paymentMethods': '支付方式分布',
    'reports.charts.trend': '收支趋势',
    'reports.empty.income': '暂无收入数据',
    'reports.empty.expense': '暂无支出数据',
    'reports.empty.payment': '暂无支付数据',
    'reports.generatedBy': '生成于 FinleyBook - 您的 AI 财务助手',

    // Subscription Page
    'subscription.limitedTime': '🔥 限时优惠',
    'subscription.title': '不只是省钱，而是让你“变富”的工具',
    'subscription.subtitle': 'FinleyBook Pro 提供每周可执行计划、无限 AI 诊断与专业报表工作流，帮助你稳定提升财务决策质量。',
    'subscription.subtitle.highlight': '',
    'subscription.averageSavings': '平均用户节省',
    'subscription.savingsAmount': '¥3000+ / 年',
    'subscription.savingsDesc': '通过 AI 比价助手 + 欲望冷却',
    'subscription.monthly': '月付',
    'subscription.yearly': '年付',
    'subscription.yearlyDiscount': '省 33%',
    'subscription.monthlyMsg': '☕️ 少喝一杯咖啡，省下一笔巨款',
    'subscription.yearlyMsg': '💰 每天仅需 <span class="text-3xl font-bold text-green-600">¥{amount}</span>',
    'subscription.bestValue': '⭐ 最超值',
    'subscription.perMonth': '/ 月',
    'subscription.save': '节省',
    'subscription.startSaving': '立即升级，解锁完整智能能力',
    'subscription.processing': '处理中...',
    'subscription.guarantee.7day': '✅ 7天无理由退款',
    'subscription.guarantee.cancel': '✅ 随时一键取消',
    'subscription.guarantee.hidden': '✅ 无隐藏费用',
    'subscription.whatYouGet': '为什么升级？',
    'subscription.faq': '常见问题',
    'subscription.faq.cancel.q': '如何取消？',
    'subscription.faq.cancel.a': '随时在个人资料中点击“取消订阅”。没有隐藏门槛，1秒完成。',
    'subscription.faq.satisfaction.q': '如果不满意怎么办？',
    'subscription.faq.satisfaction.a': '7天内全额退款，无需理由。我们对产品充满信心。',
    'subscription.faq.security.q': '我的数据安全吗？',
    'subscription.faq.security.a': '零知识加密。即使我们也无法读取您的数据。100% 隐私保证。',

    // Comparison Table
    'subscription.compare.title': '免费版 vs Pro版',
    'subscription.compare.feature': '功能特权',
    'subscription.compare.free': '免费版',
    'subscription.compare.pro': 'Pro版',
    'subscription.compare.cashback': '执行自动化',
    'subscription.compare.cashback.free': '手动',
    'subscription.compare.cashback.pro': 'AI 辅助 + 一键应用',
    'subscription.compare.withdraw': '提现额度',
    'subscription.compare.withdraw.free': '$50/月 (慢速)',
    'subscription.compare.withdraw.pro': '$500/月 (极速秒到)',
    'subscription.compare.ai': 'AI 比价助手',
    'subscription.compare.ai.free': '每日限次',
    'subscription.compare.ai.pro': '无限次 + 即时响应',
    'subscription.compare.wishlist': '心愿清单追踪',
    'subscription.compare.wishlist.free': '手动添加',
    'subscription.compare.wishlist.pro': '自动监控 + 降价提醒',
    'subscription.compare.privacy': '隐私模式',
    'subscription.compare.privacy.free': '基础',
    'subscription.compare.privacy.pro': '伪装模式 (防偷窥)',
    'subscription.compare.support': '客服支持',
    'subscription.compare.support.free': '邮件 (48小时)',
    'subscription.compare.support.pro': '在线客服 (优先通道)',

    // Testimonials
    'subscription.testimonials.title': '用户评价',
    'subscription.testimonial.1.text': '我以前从没想过购物还能反赚钱！现在每月都提一次现，感觉像在白赚。',
    'subscription.testimonial.1.author': 'Sarah J.',
    'subscription.testimonial.2.text': 'AI 比价功能帮我买电脑省了 $120，订阅费瞬间回本，太值了。',
    'subscription.testimonial.2.author': 'Mike T.',
    'subscription.testimonial.3.text': '欲望冷却功能治好了我的冲动消费，看着存款增加的感觉真好。',
    'subscription.testimonial.3.author': 'Emily R.',

    // Features
    'subscription.features.icloud.title': 'iCloud 加密备份',
    'subscription.features.icloud.desc': '零知识加密（换机数据不丢失）',
    'subscription.features.widget.title': '锁屏小组件',
    'subscription.features.widget.desc': '无需打开 App 即可记账',
    'subscription.features.lifehour.title': '生命时钟计算器',
    'subscription.features.lifehour.desc': '将价格转换为工作时长（看清真实成本）',
    'subscription.features.ai.title': 'AI 比价助手',
    'subscription.features.ai.desc': '复制商品链接，自动找低价',
    'subscription.features.camo.title': '伪装模式',
    'subscription.features.camo.desc': '摇一摇隐藏为计算器',
    'subscription.features.wishlist.title': '无限心愿清单',
    'subscription.features.wishlist.desc': '欲望冷却 + 降价追踪',
    'subscription.features.cashback.title': 'AI 工作流自动化',
    'subscription.features.cashback.desc': '将建议一键转为交易、预算和目标，并保留确认步骤',

    // Subscription Status
    'subscription.status.free': '免费版',
    'subscription.status.pro': 'Pro 会员',
    'subscription.status.current': '当前方案',
    'subscription.status.upgrade': '升级到 Pro 版',
    'subscription.status.renew': '续费时间: {date}',
    'subscription.status.cancel': '取消订阅',
    'subscription.status.free.desc': '基础功能可满足日常记账需求',
    'subscription.status.pro.desc': '享受全部高级功能',
    'subscription.features.free.limit': '月度交易记录：50 条',
    'subscription.features.free.categories': '预算分类：5 个',
    'subscription.features.free.export': '数据导出：每月 2 次',
    'subscription.features.pro.unlimited': '无限记账 • AI 分析',
    'subscription.unlock': '解锁无限功能，提升管理效率',

    // Leveling
    'level.tooltip.title': '如何提升等级',
    'level.tooltip.desc': '邀请好友即可提升等级。更高等级解锁专属徽章和奖励。',
    'level.tooltip.next': '下一等级：再邀请 {count} 位好友',

    // Insights
    'insights.title': 'AI 智能洞察',
    'insights.viewAll': '查看全部',
    'insights.highPriority': '高优先级',
    'insights.mediumPriority': '中优先级',
    'insights.lowPriority': '低优先级',
    'insights.viewAdvice': '查看建议',
    'insights.noInsights': '暂无新洞察',
    'insights.analyzing': 'AI 正在分析您的财务数据，稍后将为您提供个性化建议',

  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en') // Default to English

  // Load saved language preference on mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('finleybook-language') as Language
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh')) {
        setLanguage(savedLanguage)
      }
    }
  }, [])

  // Save language preference when changed
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('finleybook-language', lang)
    }
  }

  // Translation function with parameter support
  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key

    // Replace parameters if provided
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, String(params[param]))
      })
    }

    return translation
  }

  const value: LanguageContextType = {
    language,
    setLanguage: handleSetLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
